version: '3.4'

services:
  week5009:
    image: week5009
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
